export const sampleData = [
  {
    name: "TVSMOTOR",
    token: "8479",
    symbol: null,
    entryTime: null,
    exitTime: null,
    tickerTime: null,
    exchage: null,
    transaction: null,
    signal: null,
    ltp: 1340.45,
    pnl: 0.0,
    avgPrice: 0.0,
    realised: 0.0,
    unRealised: 0.0,
    netQty: 0,
    status: null,
    posInfo: null,
    tradingStopped: false,
  },
  {
    name: "BAJAJFINSV",
    token: "16675",
    symbol: null,
    entryTime: null,
    exitTime: null,
    tickerTime: null,
    exchage: null,
    transaction: null,
    signal: null,
    ltp: 1598.35,
    pnl: 0.0,
    avgPrice: 0.0,
    realised: 0.0,
    unRealised: 0.0,
    netQty: 0,
    status: null,
    posInfo: null,
    tradingStopped: false,
  },
  {
    name: "HINDALCO",
    token: "1363",
    symbol: null,
    entryTime: null,
    exitTime: null,
    tickerTime: null,
    exchage: null,
    transaction: null,
    signal: null,
    ltp: 424.95,
    pnl: 0.0,
    avgPrice: 0.0,
    realised: 0.0,
    unRealised: 0.0,
    netQty: 0,
    status: null,
    posInfo: null,
    tradingStopped: false,
  },
  {
    name: "ADANIPORTS",
    token: "15083",
    symbol: null,
    entryTime: null,
    exitTime: null,
    tickerTime: null,
    exchage: null,
    transaction: null,
    signal: null,
    ltp: 730.0,
    pnl: 0.0,
    avgPrice: 0.0,
    realised: 0.0,
    unRealised: 0.0,
    netQty: 0,
    status: null,
    posInfo: null,
    tradingStopped: false,
  },
  {
    name: "AUROPHARMA",
    token: "275",
    symbol: null,
    entryTime: null,
    exitTime: null,
    tickerTime: null,
    exchage: null,
    transaction: null,
    signal: null,
    ltp: 737.05,
    pnl: 0.0,
    avgPrice: 0.0,
    realised: 0.0,
    unRealised: 0.0,
    netQty: 0,
    status: null,
    posInfo: null,
    tradingStopped: false,
  },
  {
    name: "ADANIGREEN",
    token: "3563",
    symbol: null,
    entryTime: null,
    exitTime: null,
    tickerTime: null,
    exchage: null,
    transaction: null,
    signal: null,
    ltp: 964.15,
    pnl: 0.0,
    avgPrice: 0.0,
    realised: 0.0,
    unRealised: 0.0,
    netQty: 0,
    status: null,
    posInfo: null,
    tradingStopped: false,
  },
  {
    name: "M&M",
    token: "2031",
    symbol: null,
    entryTime: null,
    exitTime: null,
    tickerTime: null,
    exchage: null,
    transaction: null,
    signal: null,
    ltp: 1568.85,
    pnl: 0.0,
    avgPrice: 0.0,
    realised: 0.0,
    unRealised: 0.0,
    netQty: 0,
    status: null,
    posInfo: null,
    tradingStopped: false,
  },
  {
    name: "CIPLA",
    token: "694",
    symbol: null,
    entryTime: null,
    exitTime: null,
    tickerTime: null,
    exchage: null,
    transaction: null,
    signal: null,
    ltp: 1026.65,
    pnl: 0.0,
    avgPrice: 0.0,
    realised: 0.0,
    unRealised: 0.0,
    netQty: 0,
    status: null,
    posInfo: null,
    tradingStopped: false,
  },
];
